#!/usr/bin/env node

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { register as completionEntryDetails } from "./tools/completionEntryDetails.js";
import { register as completionInfo } from "./tools/completionInfo.js";
import { register as definition } from "./tools/definition.js";
import { register as definitionAndBoundSpan } from "./tools/definitionAndBoundSpan.js";
import { register as docCommentTemplate } from "./tools/docCommentTemplate.js";
import { register as documentHighlights } from "./tools/documentHighlights.js";
import { register as extractConstant } from "./tools/extractConstant.js";
import { register as extractFunction } from "./tools/extractFunction.js";
import { register as extractType } from "./tools/extractType.js";
import { register as fileReferences } from "./tools/fileReferences.js";
import { register as findSourceDefinition } from "./tools/findSourceDefinition.js";
import { register as format } from "./tools/format.js";
import { register as mapCode } from "./tools/mapCode.js";
import { register as references } from "./tools/references.js";
import { register as getApplicableRefactors } from "./tools/getApplicableRefactors.js";
import { register as getCombinedCodeFix } from "./tools/getCombinedCodeFix.js";
import { register as getCodeFixes } from "./tools/getCodeFixes.js";
import { register as getDiagnostics } from "./tools/getDiagnostics.js";
import { register as getMoveToRefactoringFileSuggestions } from "./tools/getMoveToRefactoringFileSuggestions.js";
import { register as getOutliningSpans } from "./tools/getOutliningSpans.js";
import { register as getSupportedCodeFixes } from "./tools/getSupportedCodeFixes.js";
import { register as selectionRange } from "./tools/selectionRange.js";
import { register as implementation } from "./tools/implementation.js";
import { register as inferReturnType } from "./tools/inferReturnType.js";
import { register as inlineVariable } from "./tools/inlineVariable.js";
import { register as moveSymbol } from "./tools/moveSymbol.js";
import { register as navtree } from "./tools/navtree.js";
import { register as navto } from "./tools/navto.js";
import { register as organizeImports } from "./tools/organizeImports.js";
import { register as prepareCallHierarchy } from "./tools/prepareCallHierarchy.js";
import { register as projectInfo } from "./tools/projectInfo.js";
import { register as provideCallHierarchyIncomingCalls } from "./tools/provideCallHierarchyIncomingCalls.js";
import { register as provideCallHierarchyOutgoingCalls } from "./tools/provideCallHierarchyOutgoingCalls.js";
import { register as provideInlayHints } from "./tools/provideInlayHints.js";
import { register as quickinfo } from "./tools/quickinfo.js";
import { register as renameFileOrDirectory } from "./tools/renameFileOrDirectory.js";
import { register as rename } from "./tools/rename.js";
import { register as signatureHelp } from "./tools/signatureHelp.js";
import { register as todoComments } from "./tools/todoComments.js";
import { register as typeDefinition } from "./tools/typeDefinition.js";

const server = new McpServer({
  name: "ts-mcp-server",
  version: "1.0.0",
});

renameFileOrDirectory(server);
rename(server);
getDiagnostics(server);
references(server);
organizeImports(server);
getCodeFixes(server);
extractFunction(server);
extractConstant(server);
moveSymbol(server);
inlineVariable(server);
extractType(server);
inferReturnType(server);
quickinfo(server);
navtree(server);
definition(server);
navto(server);
fileReferences(server);
prepareCallHierarchy(server);
provideCallHierarchyIncomingCalls(server);
provideCallHierarchyOutgoingCalls(server);
typeDefinition(server);
implementation(server);
projectInfo(server);
completionInfo(server);
completionEntryDetails(server);
signatureHelp(server);
documentHighlights(server);
getApplicableRefactors(server);
docCommentTemplate(server);
getOutliningSpans(server);
provideInlayHints(server);
getCombinedCodeFix(server);
todoComments(server);
definitionAndBoundSpan(server);
findSourceDefinition(server);
selectionRange(server);
format(server);
getMoveToRefactoringFileSuggestions(server);
getSupportedCodeFixes(server);
mapCode(server);

const transport = new StdioServerTransport();
await server.connect(transport);
